language: android
jdk: oraclejdk8
sudo: true
env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_BUILD_TOOLS_VERSION=26.0.1
    - ANDROID_API_LEVEL=22
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-${ANDROID_BUILD_TOOLS_VERSION}
  - android-${ANDROID_API_LEVEL}
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
  - sys-img-${ANDROID_ABI}-google_apis-${ANDROID_API_LEVEL}

before_script:
  # If permission for Gradlew Dependencies fail, use this.
  - sudo chmod +x ./gradlew
script:
  - echo no | android create avd --force -n test -t ${ANDROID_TARGET} --abi ${ANDROID_ABI}
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck